// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmvjpyqcumhjzrqjxync.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tdmpweXFjdW1oanpycWp4eW5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2Njk5NjYsImV4cCI6MjA3MzI0NTk2Nn0.LQEpXgsvDaWLCqMbyV9olh6tkopRdSoIhaxVYqrOMAc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});